version: "3.9"

services:
  flutter-web:
    container_name: jonosokti-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80" # container 80, host 3001
    restart: unless-stopped
