version: "3.9"

services:
  flutter-web:
    container_name: jonosokti-admin
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:8081" # host port 3001 → container port 8081
    restart: unless-stopped
