server {
    listen 80;
    server_name admin.jonosokti.com;

    root /usr/share/nginx/html;
    index index.html;

    # Flutter web routing fallback
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optional gzip for faster load
    gzip on;
    gzip_types text/plain text/css application/javascript application/json image/svg+xml;
}